### ISSUE TITLE
FC的 backward 有错

### ISSUE THREAD

**Issue by Ucag** [hanbt/learn_dl#3]
delta 应该是等于 self.activator.backward(self.ouput) * np.dot(self.W.T, delta_arry) 吧，你写成了  input 。

**Comment by hanbt** [comment]
没有错，激活函数的导数就是使用输入值来计算的。

**Comment by WalterMa** [comment]
我认为：
input中保存的是此层输入向量，而sigmoid的导数是output*(1-ouput)
此处使用input真的没有错误嘛，还是我理解有误
