### ISSUE TITLE
感知机在python3环境下无法运行

### ISSUE THREAD

**Issue by hemaojie** [hanbt/learn_dl#36]
在python3下运行 报错map(lambda (x, w): x * w,
               ^
SyntaxError: invalid syntax  不知为何？

**Comment by endrol** [comment]
python3 不支持lambda输入tuple

**Comment by xinghalo** [comment]
修改三个地方：
1 lambda (x,w):x*w 替换成 lambda x : x[0]*x[1]
2 reduce 增加引用 from functools import reduce
3 梯度更新map返回的不是list，修改成：self.weights = [w + rate * delta * x for (x, w) in zip(input_vec, self.weights)]

**Comment by hanbt** [comment]
fixed
